export const Dados = [
  {
    id: 1,
    image: "images/Fundo do Mar.png",
    nome: "Fundo do Mar",
    descricao:
      "Produzido com material de altíssima qualidade e costura excelente.",
    descricaoBojo: "Bojo: Não",
    descricaoMaterial: "Material: Tecido Trilobal 85% Poliamida 15% Elastano.",
    precoOriginal: 105,
    precoDesconto: 84.0,
    desconto: 20,
    parcelamento: "ou em até 2x de R$42,00 sem juros",
    descricaoTamanho: "Escolha o tamanho",
    size: ["P", "M", "G", "GG"],
    buttonSacola: "Adicionar ao Carrinho",
    selectSize: "",
  },

  {
    id: 2,
    nome: "Tiras",
    descricao:
      "Produzido com material de altíssima qualidade e costura excelente.",
    descricaoBojo: "Bojo: Sim",
    descricaoMaterial:
      "Material: Tecido texturizado 90% Poliamida 10% Elastano",
    image: "images/Tiras.png",
    precoOriginal: "",
    precoDesconto: 100.0,
    desconto: "",
    parcelamento: "ou em até 2x de R$50,00 sem juros",
    descricaoTamanho: "Escolha o tamanho",
    size: ["P", "M", "G", "GG"],
    buttonSacola: "Adicionar ao Carrinho",
    selectSize: "",
  },

  {
    id: 3,
    nome: "Crochê",
    descricao:
      "Produzido com material de altíssima qualidade e costura excelente.",
    descricaoBojo: "Bojo: Sim",
    descricaoMaterial: "Material: 100% Poliéster",
    image: "images/Croche.png",
    precoOriginal: "",
    precoDesconto: 95.0,
    desconto: "",
    parcelamento: "ou em até 2x de R$47,50 sem juros",
    descricaoTamanho: "Escolha o tamanho",
    size: ["P", "M", "G", "GG"],
    buttonSacola: "Adicionar ao Carrinho",
    selectSize: "",
  },

  {
    id: 4,
    nome: "Mozaico",
    descricao:
      "Produzido com material de altíssima qualidade e costura excelente.",
    descricaoBojo: "Bojo: Sim",
    descricaoMaterial: "Tecido plessê(Canelado) 94% Poliamida 6% Elastano",
    image: "images/Mozaico.png",
    precoOriginal: "",
    precoDesconto: 80.0,
    desconto: "",
    parcelamento: "ou em até 2x de R$40,00 sem juros",
    descricaoTamanho: "Escolha o tamanho",
    size: ["P", "M", "G", "GG"],
    buttonSacola: "Adicionar ao Carrinho",
    selectSize: "",
  },

  {
    id: 5,
    nome: "Babado",
    descricao:
      "Produzido com material de altíssima qualidade e costura excelente.",
    descricaoBojo: "Bojo: Sim",
    descricaoMaterial: "Tecido Anarruga 93% Poliester 7% Elastano",
    image: "images/Babado.png",
    precoOriginal: "",
    precoDesconto: 105.0,
    desconto: "",
    parcelamento: "ou em até 2x de R$52,50 sem juros",
    descricaoTamanho: "Escolha o tamanho",
    size: ["P", "M", "G", "GG"],
    buttonSacola: "Adicionar ao Carrinho",
    selectSize: "",
  },

  {
    id: 6,
    nome: "Ombro a Ombro",
    descricao:
      "Produzido com material de altíssima qualidade e costura excelente.",
    descricaoBojo: "Bojo: Sim",
    descricaoMaterial: "Tecido Trilobal 94% Poliamida 6% Elastano",
    image: "images/Ombro a Ombro.png",
    precoOriginal: "",
    precoDesconto: 85.0,
    desconto: "",
    parcelamento: "ou em até 2x de R$42,50 sem juros",
    descricaoTamanho: "Escolha o tamanho",
    size: ["P", "M", "G", "GG"],
    buttonSacola: "Adicionar ao Carrinho",
    selectSize: "",
  },

  {
    id: 7,
    nome: "Animal print",
    descricao:
      "Produzido com material de altíssima qualidade e costura excelente.",
    descricaoBojo: "Bojo: Não",
    descricaoMaterial: "Tecido Suplex 90% Poliamida 10% Elastano",
    image: "images/Animal Print.png",
    precoOriginal: 89.9,
    precoDesconto: 71.96,
    desconto: 20,
    parcelamento: "ou em até 2x de R$35,98 sem juros",
    descricaoTamanho: "Escolha o tamanho",
    size: ["P", "M", "G", "GG"],
    buttonSacola: "Adicionar ao Carrinho",
    selectSize: "",
  },

  {
    id: 8,
    nome: "Floral",
    descricao:
      "Produzido com material de altíssima qualidade e costura excelente.",
    descricaoBojo: "",
    descricaoMaterial: "Tecido Suplex 90% Poliamida 10% Elastano",
    image: "images/Floral.png",
    precoOriginal: 70,
    precoDesconto: 56.0,
    desconto: 20,
    parcelamento: "ou em até 2x de R$28,00 sem juros",
    descricaoTamanho: "Escolha o tamanho",
    size: ["P", "M", "G", "GG"],
    buttonSacola: "Adicionar ao Carrinho",
    selectSize: "",
  },

  {
    id: 9,
    nome: "Camisa",
    descricao:
      "Produzido com material de altíssima qualidade e costura excelente.",
    descricaoBojo: "Produto com leve transparência",
    descricaoMaterial:
      "Produzido com material de altíssima qualidade e costura excelente. Material: Tecido Tule 90% poliamida 10% elastano",
    image: "images/Camisa.png",
    precoOriginal: 80,
    precoDesconto: 64.0,
    desconto: 20,
    parcelamento: "ou em até 2x de R$32,00 sem juros",
    size: ["P", "M", "G", "GG"],
    buttonSacola: "Adicionar ao Carrinho",
    selectSize: "",
  },

  {
    id: 10,
    nome: "Listrado",
    descricao:
      "Produzido com material de altíssima qualidade e costura excelente.",
    descricaoBojo: "",
    descricaoMaterial:
      "Produzido com material de altíssima qualidade e costura excelente",
    image: "images/Listrado.png",
    precoOriginal: "",
    precoDesconto: 70.0,
    desconto: "",
    parcelamento: "ou em até 2x de R$35,00 sem juros",
    descricaoTamanho: "Escolha o tamanho",
    size: ["P", "M", "G", "GG"],
    buttonSacola: "Adicionar ao Carrinho",
    selectSize: "",
  },

  {
    id: 11,
    nome: "Lisa",
    descricao:
      "Produzido com material de altíssima qualidade e costura excelente.",
    descricaoBojo: "Bojo: Não",
    descricaoMaterial: "Material: Tecido Alto Crepe Georget.",
    image: "images/Lisa.png",
    precoOriginal: "",
    precoDesconto: 85.0,
    parcelamento: "ou em até 2x de R$42,50 sem juros",
    descricaoTamanho: "Escolha o tamanho",
    size: ["P", "M", "G", "GG"],
    buttonSacola: "Adicionar ao Carrinho",
    selectSize: "",
  },

  {
    id: 12,
    nome: "Abstrata",
    descricao:
      "Produzido com material de altíssima qualidade e costura excelente.",
    descricaoBojo: "Bojo: Não",
    descricaoMaterial: "Material: Tecido Tule 90% Poliamida 10% Elastano.",
    image: "images/Abstrata.png",
    precoOriginal: "",
    precoDesconto: 105.0,
    desconto: "",
    parcelamento: "ou em até 2x de R$52,50 sem juros",
    descricaoTamanho: "Escolha o tamanho",
    size: ["P", "M", "G", "GG"],
    buttonSacola: "Adicionar ao Carrinho",
    selectSize: "",
  },
];
